# Generated by Django 3.1.13 on 2024-05-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriyalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120, unique=True)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ulchov_birligi', models.CharField(choices=[('Грамм', 'Грамм'), ('Килограмм', 'Килограмм'), ('Штука', 'Штука'), ('Коробка', 'Коробка'), ('Литр', 'Литр')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kategoriyalar')),
            ],
        ),
        migrations.CreateModel(
            name='Yetkazib_beruvchilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FISH', models.CharField(max_length=120)),
                ('INN', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Omborxona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_soni', models.IntegerField()),
                ('umumiy_narx', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mahsulotlar', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kirimlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('keltirilgan_sana', models.DateField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mahsulotlar')),
                ('yetkazib_beruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.yetkazib_beruvchilar')),
            ],
        ),
        migrations.CreateModel(
            name='Chiqimlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.IntegerField()),
                ('ism', models.CharField(max_length=120)),
                ('familiya', models.CharField(max_length=120)),
                ('telefon', models.CharField(max_length=50)),
                ('sotilgan_sana', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mahsulotlar')),
            ],
        ),
    ]
