# Generated by Django 3.1.13 on 2024-05-28 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240528_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqimlar',
            name='sotilgan_sana',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
